### ISSUE TITLE
Detect unchanged serverless project for short build execution

### ISSUE THREAD

**Issue by rene84** [org-formation/org-formation-cli#109]
Currently, a task **`type: update-serverless.com`** executes the command `npx sls deploy`.

If a project is unchanged, which is often the case during build executions, the build server will still take a bit of time to install all depedencies, generate the cloudformation templates only to let CloudFormation discover that nothing has changed.

An option could be to, similar to copy-to-s3 tasks, store a hash of the entire serverless folder to detect unchanged projects

**Comment by eduardomourar** [comment]
@OlafConijn we have upgraded to version 0.9.14-beta.1, and the task still runs even when the contents of the path folder has been kept intact. there seems to be an issue with the hashing, probably related to when that happens

**Comment by OlafConijn** [comment]
hi, i looked into the issue and believe this is caused by the following:
- when update-serverless tasks run they modify the source code directory (generating a node_modules, e.g.)
- when another update-serverless task runs the same directory (but through a different include) the hash calculated for comparison includes the modified files in the source code directory.


I "fixed" this by excluding the node_modules folder when calculating the hash (in `0.9.14-beta.2`)
This however is not the best fix possible.

What it should do instead is something more along the lines of:
- package the serverless project into a directory (and have the directory name contain the hash of the source directory contents).
- make sure that no 2 tasks are packaging at the same time (using a spin-wait type of construct)
- if there already is a directory that contains the output of packaging deploy the packaged output.

This would ensure that:
- when packaging the source directory is not modified
- deployments to different accounts can be done in parallel (at the moment this is limited to 1 target max)

also note that ever since 0.9.13 there is the option to deploy lambdas directly using copy-to-s3. I would expect for a lot of scenario's where you currently might be using serverless this could be a viable alternative (and faster!)

**Comment by rene84** [comment]
This now works perfectly. Thanks!
