### ISSUE TITLE
Event from eventbridge and organization.yml must be published while honouring failure tolerance

### ISSUE THREAD

**Issue by eduardomourar** [org-formation/org-formation-cli#168]
The remote `organization.yml` is only being pushed after the last task has been completed by the `org-formation perform-tasks` command, but it should be done rather when the `update-organization` task has been completed (or you run a separate `org-formation update` command). This is somewhat more relevant in the context of a delegated build, because the other pipelines might rely on the organization structure.

**Comment by eduardomourar** [comment]
Also, because of this behavior, the organization file will not be updated if an update-stack task fails in the middle of the process. This is the case even if you increase the fail tolerance.

**Comment by OlafConijn** [comment]
Publishing the organization.yml at the end of a succesfull perform-tasks was a conscious decision. 
Imagine:

Project1:
- update-organization
- setup iam
- cross account permissions

Project2:
- compliance

Project3:
- eventing

since the file is only copied and EventBridge event is raised after 1) the organization was changed and 2) perform-tasks has successfully completed, this allows Project2 and Projec3 to assume the iam and cross account permissions have been set up properly.

it should "play nice" with failure tolerance though. that might be a bug

**Comment by OlafConijn** [comment]
should we change the title to something like: organization.yml and eventbridge event must be published if number of failures is less than or equal to the tolerance for failures? 

if i understand you correctly that seems to be an issue you ran into?

**Comment by eduardomourar** [comment]
yes, it is happening when the account creation SLS deployment is failing
