### ISSUE TITLE
update-serverless.com task default deployment is not compatible when serverless gets to v3.0.0

### ISSUE THREAD

**Issue by brianmyburgh** [org-formation/org-formation-cli#303]
Default command for running update-serverless.com task is: npm ci && npx sls deploy ${CurrentTask.Parameters} --region ${region} --stage ${stage} --config ${config} --conceal

Serverless will be dropping support for free form CLI options.  See Deprecation code: UNSUPPORTED_CLI_OPTIONS, https://www.serverless.com/framework/docs/deprecations.

Starting with v3.0.0, Serverless will report unrecognized options with a thrown error.

This means that ${CurrentTask.Parameters} in sls deploy will no longer be supported in it's current form.

**Comment by OlafConijn** [comment]
thanks @brianmyburgh, I havent read up on the changes yet. But how would parameters be passed to Serverless workloads? I would assume there to be an alternative/workaround

**Comment by brianmyburgh** [comment]
For free form process configuration options they advise to rely on environment variables instead.

PARAM1=value1 PARAM2=value2 npx sls deploy.  

So in org-formation where ${CurrentTask.Parameters} translates to --PARAM1 value1 --PARAM2 value2, could there be an alternative translation to the above form?

**Comment by davidvpe** [comment]
According to https://www.serverless.com/framework/docs/guides/upgrading-v3#breaking-changes
We can now use `serverless deploy --param="foo=bar"` meaning we only need to add "param=" to the `reduce` inside `GetParametersAsArgument` in `sls-build-task-pluing.ts` file.

The only problem is that this will be a breaking change, since it will no longer support serverless v2.x. 

I made a PR for the change above #454

**Comment by davidvpe** [comment]
Fix is available in NPM as version 1.0.9-beta.1

https://www.npmjs.com/package/aws-organization-formation/v/1.0.9-beta.1
