### ISSUE TITLE
Github Actions for CI/CD

### ISSUE THREAD

**Issue by samuelcastro** [org-formation/org-formation-cli#379]
This is a question not a bug.

Can I use Github Actions to manage deploy/update my org formation infrastructure, or it has to be through CodePipeline?

Thanks.

**Comment by OlafConijn** [comment]
yes, you can! most of the projects I am involved in run on GitHub actions. The CLI does codepipiline because it only requires AWS Credentials.

roughly the way this works:
- you would covert your build spec to a workflow file 
- you would set up a role in your AWS Account that you can assume from within your GitHub actions (either by storing creds in secrets or [OIDC ](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services))
- clone your code from CodeCommit and push it into Github

good luck!

**Comment by samuelcastro** [comment]
Awesome, thank you!

**Comment by samuelcastro** [comment]
@OlafConijn Would you have a template or a sample project using Github Actions? If not, I think creating one would be very helpful for the community.

Thanks.
